# random number
import random
randNumber = random.randint(1,100)
while True:
    urChoice = int(input('Input number which was generated by random module :'))
    if urChoice == randNumber:
        print('Congratulations u guessed it')
        break
    else:
        print('Nope. ', end='')
        if urChoice<randNumber:
            print(' Greater     ')
        else:
            print(' Lower       ')
# pi and sqrt imports
from math import sqrt
from math import pi
def rectangleSquare(side_1, side_2):
    return side_1*side_2
def triangleSquare(side_1,side_2,side_3):
    p = (side_1+side_2+side_3)/2
    return sqrt(p*(side_1-p)*(side_2-p)*(side_3-p))
def circleSquare(r):
    return 4*pi*r*r
square = int(input('Input object - 1:rectanle 2:triangle  3:circle'))
if square == 1:
    side_1  = int(input('Input 1 side of rectangle : '))
    side_2  = int(input('Input 2 side of rectangle : '))
    print('S = {0} * {1} = {2}'.format(side_1,side_2,rectangleSquare(side_1,side_2)))
elif square == 2:
    side_1 =  int(input('Input 1 side of triangle : '))
    side_2 =  int(input('Input 2 side of triangle : '))
    side_3 =  int(input('Input 3 side of triangle : '))
    print('S = {0}'.format(triangleSquare(side_1,side_2,side_3)))
elif square == 3:
    r = int(input('Input R of circle : '))
    print('S = 4*\u03C0*{0}\U000000B2 =  {1}'.format(r,circleSquare(r)))
else:
    print('Unknown symbol')

#weather and pyowm module
import pyowm



city=input("What city you are interested:")
owm = pyowm.OWM('ef2206ff5da67de63306d0b143e20872')
# Have a pro subscription? Then use:
# owm = pyowm.OWM(API_key='your-API-key', subscription_type='pro')
# Search for current weather in the city

observation = owm.weather_at_place(city)
w = observation.get_weather()
temperature=w.get_temperature('celsius')['temp']
humidity = w.get_humidity()
pressure = w.get_pressure()
clouds = w.get_clouds()
winds  = w.get_wind()
print("In " + city + " city" + " is the temperature of the air" + " " + str(temperature) + " for the Celsius" + '\nCloudness  -  '+str(clouds)+'%' + '\nWind speed  - '+str(winds['speed']) + '\nHumidity   -  '+str(humidity)+ '%' )
print("In this city "+ w.get_detailed_status())